"""Authentication client for E-Distribuzione.

The portal answers on two hostnames of the same Salesforce org: the custom one
(private.e-distribuzione.it) is behind Imperva and blocks non-browser clients,
so when it returns the anti-bot page login and token refresh fall back to the
canonical domain (edistribuzione.my.site.com) - same login, same community,
without the anti-bot check. The primary stays the custom domain, so the client
returns to it by itself once the block is lifted. Details in const.py.

Standard OAuth2 Authorization Code + PKCE login, but the hard part is in the
middle: the credentials are submitted via an Aura action (Salesforce
Lightning), and the OTP goes through a classic Visualforce "Login Flow" page
(ViewState/RichFaces). These are UI implementation details, not a stable public
API: this module scrapes HTML/JSON with regexes, and WILL BREAK if Enel changes
the Experience Cloud template or the RichFaces version. The most fragile parts
are the static scraping functions at the bottom of the file - the first place to
check if login starts failing.

Once a refresh_token is obtained, this fragility is no longer needed:
AuthClient.async_refresh_access_token() talks only to the standard OAuth2
endpoint.

async_begin_login runs in sequence:
    1. _carica_pagina_login       GET /oauth2/authorize (PKCE) -> login page
    2. _invia_credenziali         POST Aura loginUser -> frontdoor.jsp URL
    3. _segui_a_pagina_otp        GET frontdoor -> JS bridge -> OTP page
    4. _async_avvia_invio_otp     empty submit: actually triggers the OTP send

async_submit_otp then runs:
    5. _sottometti_codice_otp          POST the form with the OTP -> meta Location
    6. _scarica_pagina_dopo_otp        follow that redirect
    7. _estrai_codice_autorizzazione   find code/state (handling the OAuth
                                        consent on the very first authorization)
    8. _async_exchange_code            POST /oauth2/token
"""
from __future__ import annotations

import asyncio
import base64
import hashlib
import html as html_lib
import json
import logging
import re
import secrets
import uuid
from dataclasses import dataclass, field
from pathlib import Path
from urllib.parse import unquote

import aiohttp

from .const import (
    AURA_ENDPOINT,
    LOGINFLOW_URL,
    OAUTH_AUTHORIZE_URL,
    OAUTH_CLIENT_ID,
    OAUTH_REDIRECT_URI,
    OAUTH_SCOPE,
    OAUTH_TOKEN_URL,
    SF_HOST_DIRETTO,
    SF_HOST_PRINCIPALE,
    SF_HOSTS,
)

_LOGGER = logging.getLogger(__name__)

_MOBILE_USER_AGENT = "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15"

_MAX_REDIRECT_HOPS = 15

# Fallback field names of the login flow RichFaces form, used only if
# _analizza_pagina_otp cannot discover them dynamically from the real page (the
# "thePage:j_id2:..." prefixes are generated by Salesforce and can change
# between deploys).
_CAMPO_OTP_INPUT_DEFAULT = "thePage:j_id2:i:f:pb:d:element___input____OTP_Input"
_CAMPO_RICHIEDI_NUOVO_OTP_DEFAULT = "thePage:j_id2:i:f:pb:d:element___hidden____Richiedi_nuovo_OTP"
_CAMPO_NEXT_AJAX_DEFAULT = "thePage:j_id2:i:f:pb:pbb:nextAjax"

# Fragments with which the portal signals that the account has too many sessions
# open at once ("Hai superato il numero di sessioni simultanee consentite"). It
# must be told apart from wrong credentials and from a markup change: in this
# state the login does not proceed and the OTP is not even sent, so the user
# would be left waiting for a code that never arrives.
_MARCATORI_TROPPE_SESSIONI = (
    "sessioni simultanee",
    "sessioni contemporanee",
    "numero di sessioni",
    "sessioni consentite",
)

# Pages of Imperva's (Incapsula) anti-bot protection, which answers in place of
# the login and token endpoints when it classifies the traffic as automated: the
# "Pardon Our Interruption" JavaScript check (HTTP 200) and the "Incapsula
# incident ID" block. Only markers of these two pages: the _Incapsula_Resource
# script can also appear on normal pages of a protected site.
_MARCATORI_ANTIBOT = (
    "pardon our interruption",
    "incapsula incident id",
)

# Text with which the response to the first form submit confirms it has sent the
# code (e.g. "Abbiamo inviato un codice a 5 cifre al tuo indirizzo email").
# Several variants because the channel (email/SMS) and the wording change from
# account to account: a missing confirmation is NOT treated as a fatal error (it
# would break otherwise valid logins with a different wording), only reported.
_MARCATORI_OTP_INVIATO = (
    "abbiamo inviato",
    "inviato un codice",
    "codice a 5 cifre",
    "codice è stato inviato",
    "nuovo codice",
)

# Labels of the button that APPROVES on the OAuth consent screen. On the real
# page the two buttons share the SAME name="save" and differ only by value:
# "Consenti" approves, " Nega " (with the spaces) rejects - the wrong button
# means denying the integration's authorization, so the value is compared in
# full, not searched as a substring.
_ETICHETTE_CONSENSO = ("consenti", "allow", "approve", "autorizza", "accetta")


def _contiene(testo: str, marcatori: tuple[str, ...]) -> bool:
    minuscolo = testo.lower()
    return any(marcatore in minuscolo for marcatore in marcatori)


def _scrivi_pagina_debug(html: str, nome_file: str) -> None:
    try:
        percorso = Path(nome_file)
        percorso.write_text(html, encoding="utf-8")
    except OSError as exc:
        _LOGGER.debug("Impossibile salvare %s su disco: %s", nome_file, exc)
        return
    _LOGGER.error("Pagina completa salvata in %s", percorso.resolve())


def _salva_pagina_debug(html: str, nome_file: str) -> None:
    """Write the page to disk (best-effort) and log its path, so it can be
    requested in a bug report without having to capture a HAR.

    The write is delegated to an executor when we are inside Home Assistant's
    event loop, which flags synchronous I/O as a "blocking call". Outside an
    event loop (tests, scripts/verify_login.py) it writes directly.
    """
    try:
        loop = asyncio.get_running_loop()
    except RuntimeError:
        _scrivi_pagina_debug(html, nome_file)
        return
    # Deliberately not awaited: it is a best-effort diagnostic dump, it must not
    # slow down or fail the login if the disk is slow or full.
    loop.run_in_executor(None, _scrivi_pagina_debug, html, nome_file)


def _log_parsing_failure_context(html: str, campo_cercato: str) -> None:
    """Log the page title + a preview when an expected field is not found - tells
    "wrong regex" (the field is there but in a different form) from "page
    completely different from the expected one" without having to ask for another
    capture. Also saves the whole page to disk."""
    title_match = re.search(r"<title>(.*?)</title>", html, re.IGNORECASE | re.DOTALL)
    title = title_match.group(1).strip() if title_match else "(nessun <title> trovato)"
    _LOGGER.error(
        "Campo '%s' non trovato. Titolo pagina: %r. Lunghezza: %d caratteri. "
        "Primi 300 caratteri: %r",
        campo_cercato,
        title,
        len(html),
        html[:300],
    )
    _salva_pagina_debug(html, "otp_page_debug.html")


class AuthError(Exception):
    """Generic authentication error."""


class InvalidCredentials(AuthError):
    """Wrong email or password."""


class InvalidOtp(AuthError):
    """Wrong or expired OTP code."""


class TroppeSessioni(AuthError):
    """The account already has too many open sessions: the portal refuses the
    login before sending any OTP.

    It is not a credentials problem nor a markup change: until the other sessions
    are closed or expire (official app, website, previous attempts of this same
    integration) there is nothing to re-enter in the form, a session must be
    freed and the login retried.
    """


class AccessoBloccato(AuthError):
    """E-Distribuzione answered with Imperva's anti-bot page instead of the
    expected one: automated access is blocked server-side.

    It is not a credentials problem nor a markup change, and there is nothing to
    fix here: it must be reported clearly and retried later, without insisting.
    """


def _verifica_non_bloccato(testo: str) -> None:
    """Raise AccessoBloccato if the response is the anti-bot page."""
    if _contiene(testo, _MARCATORI_ANTIBOT):
        raise AccessoBloccato("E-Distribuzione ha risposto con la pagina antibot (Imperva)")


async def _leggi_testo(resp: aiohttp.ClientResponse) -> str:
    """Response body, after ruling out the anti-bot page."""
    testo = await resp.text()
    _verifica_non_bloccato(testo)
    return testo


class ParsingError(AuthError):
    """The scraped page did not contain what was expected.

    Most likely cause: Enel changed something in their Salesforce site and the
    regexes below need updating. Capture a fresh HAR and compare.
    """


def _identita(url: str) -> str:
    return url


async def _get_following_redirects(
    session: aiohttp.ClientSession,
    url: str,
    *,
    params: dict | None = None,
    headers: dict | None = None,
    riscrivi=_identita,
) -> aiohttp.ClientResponse:
    """GET following the redirects by hand instead of allow_redirects=True.

    Needed because the /services/oauth2/authorize redirect chain goes through a
    'startURL' parameter that contains a percent-encoded nested URL. Letting
    aiohttp handle the redirects itself, the behaviour depends on how the library
    re-encodes an already-encoded URL at each hop and can enter an infinite loop
    (TooManyRedirects). Following the redirects explicitly with encoded=True on
    the next hop's URL, the Location value is never re-processed: the same chain
    that loops with allow_redirects=True resolves here in a few hops.

    'riscrivi' rewrites each hop's URL onto the active host (see
    AuthClient._su_host): a Location can point to the custom domain behind
    Imperva, and following it as-is would land on the anti-bot page instead of
    the destination.

    Returns the final response (status < 300, no further Location); the caller is
    responsible for closing/consuming 'resp' as usual.
    """
    resp = await session.get(url, params=params, headers=headers, allow_redirects=False)

    for _ in range(_MAX_REDIRECT_HOPS):
        location = resp.headers.get("Location")
        if location is None:
            return resp

        resp.close()
        location_url = aiohttp.client.URL(location, encoded=True)
        next_url = location_url if location_url.is_absolute() else resp.url.join(location_url)
        next_url = aiohttp.client.URL(riscrivi(str(next_url)), encoded=True)
        resp = await session.get(next_url, headers=headers, allow_redirects=False)

    resp.close()
    raise AuthError(
        f"Troppi redirect (>{_MAX_REDIRECT_HOPS}) seguendo {url}: possibile "
        "cambiamento lato Salesforce nella struttura dei redirect di login."
    )


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _make_pkce_pair() -> tuple[str, str]:
    verifier = _b64url(secrets.token_bytes(32))
    challenge = _b64url(hashlib.sha256(verifier.encode("ascii")).digest())
    return verifier, challenge


@dataclass
class _LoginFlowState:
    """Everything needed to carry from the OTP page to its submission."""

    fwuid: str | None = None
    aura_token: str | None = None
    view_state: str | None = None
    view_state_version: str | None = None
    view_state_mac: str | None = None
    view_state_csrf: str | None = None
    form_action_url: str | None = None
    # The prefixes of the fields under 'thePage:j_id2:i:f:...' are generated by
    # Salesforce and vary between deploys: the name discovered on the real page
    # is kept instead of assuming the hardcoded ones (used only as a fallback in
    # the respective form builders).
    otp_field_name: str | None = None
    resend_field_name: str | None = None
    # The visible "Richiedi nuovo OTP" checkbox, twin of the hidden field above:
    # used only for an explicit resend, where we reproduce a browser's submit
    # with the box ticked.
    resend_checkbox_field_name: str | None = None
    next_field_name: str | None = None


@dataclass
class OAuthTokens:
    access_token: str
    refresh_token: str
    instance_url: str
    id_token: str | None = None
    raw: dict = field(default_factory=dict)


class AuthClient:
    """Drives the login -> OTP -> OAuth code -> token exchange sequence."""

    def __init__(self, session: aiohttp.ClientSession) -> None:
        self._session = session
        self._code_verifier: str | None = None
        self._oauth_state: str | None = None
        self._flow = _LoginFlowState()
        # Active Salesforce host. Starts as the primary (custom) domain and
        # switches to the direct one only when the primary is blocked by the
        # anti-bot check (see async_begin_login/async_refresh_access_token).
        self._host = SF_HOST_PRINCIPALE
        # True/False after async_begin_login()/async_resend_otp() depending on
        # whether the portal confirmed the code was sent; None until we got
        # there. The config flow uses it to warn the user instead of leaving
        # them waiting for an OTP that will never arrive.
        self.otp_invio_confermato: bool | None = None

    @property
    def _origin(self) -> str:
        return f"https://{self._host}"

    def _su_host(self, url: str) -> str:
        """Rewrite a URL onto the active host.

        The module constants and the URLs the server generates point to the
        custom domain; when the client has switched to the direct host, every
        URL must be rewritten onto it, or the next request would land back on
        the blocked domain. Relative URLs or other hosts pass through unchanged.
        """
        for host in SF_HOSTS:
            prefisso = f"https://{host}"
            if url.startswith(prefisso):
                return f"https://{self._host}" + url[len(prefisso):]
        return url

    # -- Steps 1-4: login + OTP -------------------------------------------

    async def async_begin_login(self, email: str, password: str) -> None:
        """Submit email/password and reach the OTP page ready for validation.
        Raises an exception if the credentials are rejected.

        Tries the primary host first; if it is blocked by the anti-bot check
        (AccessoBloccato), restarts on the direct host. The block hits at the
        first step, before any OTP is sent, so restarting wastes no code; the
        following steps (async_submit_otp) keep using the host that worked.

        Always assumes an OTP step follows.
        """
        self._host = SF_HOST_PRINCIPALE
        try:
            await self._async_begin_login_su_host(email, password)
        except AccessoBloccato:
            if self._host == SF_HOST_DIRETTO:
                raise
            _LOGGER.warning(
                "Login bloccato su %s, riprovo via %s", SF_HOST_PRINCIPALE, SF_HOST_DIRETTO
            )
            self._host = SF_HOST_DIRETTO
            self._flow = _LoginFlowState()
            self.otp_invio_confermato = None
            await self._async_begin_login_su_host(email, password)

    async def _async_begin_login_su_host(self, email: str, password: str) -> None:
        login_page_html, start_url_value, aura_page_uri, referer = (
            await self._carica_pagina_login(email)
        )
        frontdoor_url = await self._invia_credenziali(
            email, password, login_page_html, start_url_value, aura_page_uri, referer
        )
        otp_page_html = await self._segui_a_pagina_otp(frontdoor_url)
        self._analizza_pagina_otp(otp_page_html)
        await self._async_avvia_invio_otp()

    async def _carica_pagina_login(self, email: str) -> tuple[str, str, str, str]:
        """Step 1: GET /oauth2/authorize with PKCE, following the redirects by
        hand (see _get_following_redirects) to the Salesforce login page. Also
        generates code_verifier/oauth_state used later.

        Returns (login_page_html, start_url_value, aura_page_uri, referer).
        """
        self._code_verifier, code_challenge = _make_pkce_pair()
        self._oauth_state = _b64url(secrets.token_bytes(16))

        headers = {"User-Agent": _MOBILE_USER_AGENT}
        params = {
            "prompt": "login",
            "nonce": _b64url(secrets.token_bytes(16)),
            "display": "touch",
            "response_type": "code",
            "scope": OAUTH_SCOPE,
            "login_hint": email,
            "code_challenge": code_challenge,
            "code_challenge_method": "S256",
            "redirect_uri": OAUTH_REDIRECT_URI,
            "client_id": OAUTH_CLIENT_ID,
            "state": self._oauth_state,
        }

        resp = await _get_following_redirects(
            self._session,
            self._su_host(OAUTH_AUTHORIZE_URL),
            params=params,
            headers=headers,
            riscrivi=self._su_host,
        )
        login_page_html = await _leggi_testo(resp)
        # The 'startURL' parameter of the page we land on contains a 'source=...'
        # token generated by the server on the first hop, which the server
        # requires back in the 'startUrl' field of the next step to validate that
        # the login belongs to the same authorization flow: sending a bare path
        # (without this token) produces a generic AuraClientInputException.
        start_url_value = resp.url.query.get(
            "startURL", "/PortaleClienti/setup/secur/RemoteAccessAuthorizationPage.apexp"
        )
        aura_page_uri = resp.url.path_qs
        referer = str(resp.url)
        resp.close()
        return login_page_html, start_url_value, aura_page_uri, referer

    async def _invia_credenziali(
        self,
        email: str,
        password: str,
        login_page_html: str,
        start_url_value: str,
        aura_page_uri: str,
        referer: str,
    ) -> str:
        """Step 2: extract fwuid/loaded from the login page, submit the Aura
        loginUser action, and return the frontdoor.jsp URL to follow."""
        headers = {"User-Agent": _MOBILE_USER_AGENT}

        self._flow.fwuid = self._estrai_fwuid(login_page_html)
        loaded = self._estrai_loaded(login_page_html)
        # aura.token: for this specific action the client literally sends the
        # string "null" (not a real token), and the server accepts it
        # ("state":"SUCCESS"). Presumably there is no authenticated session to
        # protect via CSRF at this point of the flow yet.
        self._flow.aura_token = "null"

        # json.dumps instead of string concatenation: avoids malformed JSON if
        # the email/password contained quotes or backslashes.
        message = json.dumps({
            "actions": [{
                "id": "1;a",
                "descriptor": "apex://PED_LoginController/ACTION$loginUser",
                "callingDescriptor": "markup://c:PED_Login",
                "params": {
                    "username": email,
                    "password": password,
                    "startUrl": start_url_value,
                },
            }]
        })
        # 'loaded' must NOT be {} (empty): the server replies with a generic
        # AuraClientInputException if it does not match what it expects - it
        # contains a reference to the loaded component version (e.g.
        # {"APPLICATION@markup://siteforce:loginApp2":"..."}).
        aura_context = json.dumps({
            "mode": "PROD",
            "fwuid": self._flow.fwuid,
            "app": "siteforce:loginApp2",
            "loaded": json.loads(loaded),
            "dn": [],
            "globals": {},
            "uad": True,
        })
        data = {
            "message": message,
            "aura.context": aura_context,
            "aura.pageURI": aura_page_uri,
            "aura.token": self._flow.aura_token,
        }

        # X-SFDC-Page-Scope-Id: never seen in any server response, only in
        # requests - presumably generated client-side (a correlation id reused
        # identically on all Aura calls). Origin/Referer/Content-Type: present in
        # the request, not individually confirmed as necessary but zero-risk to
        # add.
        login_headers = {
            **headers,
            "X-SFDC-Page-Scope-Id": str(uuid.uuid4()),
            "Content-Type": "application/x-www-form-urlencoded;charset=UTF-8",
            "Origin": self._origin,
            "Referer": referer,
        }

        async with self._session.post(
            f"{self._su_host(AURA_ENDPOINT)}?r=2&other.PED_Login.loginUser=1",
            data=data,
            headers=login_headers,
        ) as resp:
            raw_text = await _leggi_testo(resp)
            try:
                payload = json.loads(raw_text)
            except json.JSONDecodeError as err:
                _LOGGER.error(
                    "Risposta non-JSON da loginUser (status %s). Primi 500 "
                    "caratteri del corpo: %r",
                    resp.status,
                    raw_text[:500],
                )
                raise ParsingError(
                    f"Risposta non-JSON da loginUser (status {resp.status}): "
                    f"{raw_text[:200]!r}"
                ) from err

        try:
            return_value = payload["actions"][0]["returnValue"]
        except (KeyError, IndexError) as err:
            raise ParsingError("Forma inattesa della risposta di loginUser") from err

        if not isinstance(return_value, str) or not return_value.startswith("OK:"):
            # The concurrent session limit arrives here as an error message of
            # the same login action: treating it as "invalid credentials" would
            # send the user to recheck email and password while the problem is
            # elsewhere.
            self._verifica_non_troppe_sessioni(str(return_value))
            raise InvalidCredentials(str(return_value))

        # Following it establishes the 'sid' session cookie and lands on a bridge
        # page that redirects via JAVASCRIPT (not HTTP) to the real OTP form -
        # see _segui_a_pagina_otp. The URL comes back on the custom domain:
        # rewrite it onto the active host.
        return self._su_host(return_value[len("OK:") :])

    async def _segui_a_pagina_otp(self, frontdoor_url: str) -> str:
        """Step 3: frontdoor.jsp establishes the 'sid' session cookie and lands
        on a bridge page that redirects via JAVASCRIPT
        (window.location.replace(...), not an HTTP redirect) to the real OTP
        form - a browser follows it automatically, here it must be extracted and
        followed by hand.
        """
        headers = {"User-Agent": _MOBILE_USER_AGENT}

        resp = await _get_following_redirects(
            self._session, frontdoor_url, headers=headers, riscrivi=self._su_host
        )
        bridge_html = await _leggi_testo(resp)
        resp.close()

        otp_form_url = self._su_host(self._estrai_url_redirect_js(bridge_html))
        resp = await _get_following_redirects(
            self._session, otp_form_url, headers=headers, riscrivi=self._su_host
        )
        otp_page_html = await _leggi_testo(resp)
        resp.close()
        return otp_page_html

    async def _async_avvia_invio_otp(self) -> None:
        """Step 4: the OTP form does not start on its own when the page loads - a
        first button submit, WITHOUT a code, is needed to actually send it (the
        response contains "Abbiamo inviato un codice a 5 cifre al tuo indirizzo
        email", not only SMS despite the field name)."""
        await self._async_post_form_otp(self._form_invio_iniziale())

    async def async_resend_otp(self) -> bool:
        """Have a new OTP re-sent WITHIN the already started login session.

        Needed because an OTP generated elsewhere (official app or website)
        belongs to another Salesforce login flow "interview" and cannot be
        validated here: if the code does not arrive, the only way to get a valid
        one is to have it re-sent from this same session.

        Returns True if the portal confirmed the send.
        """
        if self._flow.view_state is None:
            raise AuthError("async_begin_login() deve riuscire prima di async_resend_otp()")
        await self._async_post_form_otp(self._form_richiedi_nuovo())
        return bool(self.otp_invio_confermato)

    def _campi_comuni_form_otp(self) -> dict[str, str]:
        """RichFaces fields common to all login flow submits (initial send,
        resend, validation): only the OTP field and the resend flag change,
        handled by the three builders below."""
        next_field = self._flow.next_field_name or _CAMPO_NEXT_AJAX_DEFAULT
        return {
            "AJAXREQUEST": "_viewRoot",
            "thePage:j_id2:i:f": "thePage:j_id2:i:f",
            "thePage:j_id2:i:f:pb:d:navigationType": "",
            "com.salesforce.visualforce.ViewState": self._flow.view_state,
            "com.salesforce.visualforce.ViewStateVersion": self._flow.view_state_version,
            "com.salesforce.visualforce.ViewStateMAC": self._flow.view_state_mac,
            "com.salesforce.visualforce.ViewStateCSRF": self._flow.view_state_csrf,
            next_field: next_field,
        }

    def _form_invio_iniziale(self) -> dict[str, str]:
        """First submit, empty: no OTP field nor resend flag - a "neutral" submit
        of the just-loaded form, which is what actually triggers the code send
        (see _async_avvia_invio_otp)."""
        return self._campi_comuni_form_otp()

    def _form_richiedi_nuovo(self) -> dict[str, str]:
        """Submit requesting a new code: sets the resend flag (hidden field) plus
        the visible checkbox that mirrors it, if known - see the comment on the
        two same-named fields in _analizza_pagina_otp."""
        dati = self._campi_comuni_form_otp()
        dati[self._flow.resend_field_name or _CAMPO_RICHIEDI_NUOVO_OTP_DEFAULT] = "true"
        if self._flow.resend_checkbox_field_name:
            dati[self._flow.resend_checkbox_field_name] = "true"
        return dati

    def _form_convalida(self, otp_code: str) -> dict[str, str]:
        """Submit with the code to validate."""
        dati = self._campi_comuni_form_otp()
        dati[self._flow.otp_field_name or _CAMPO_OTP_INPUT_DEFAULT] = otp_code
        dati[self._flow.resend_field_name or _CAMPO_RICHIEDI_NUOVO_OTP_DEFAULT] = "false"
        return dati

    async def _async_post_form_otp(self, data: dict[str, str]) -> None:
        """Submit of the OTP form that does NOT carry a code to validate (initial
        send or resend): checks that the portal actually sent the OTP and updates
        ViewState/CSRF from the response.

        The tokens in THIS call's response are the ones to use for the actual
        code submission (async_submit_otp), not those of the landing page: they
        rotate on every form submit.
        """
        headers = {"User-Agent": _MOBILE_USER_AGENT, "Faces-Request": "partial/ajax"}
        url = self._su_host(self._flow.form_action_url or LOGINFLOW_URL)
        async with self._session.post(url, data=data, headers=headers) as resp:
            body = await _leggi_testo(resp)

        self._verifica_non_troppe_sessioni(body, "otp_send_debug.html")

        self.otp_invio_confermato = _contiene(body, _MARCATORI_OTP_INVIATO)
        if not self.otp_invio_confermato:
            # Deliberately not fatal: the page might confirm the send with words
            # we do not know yet, and aborting here would break otherwise valid
            # logins. But it must be reported, because the other possibility is
            # that the code was NEVER sent.
            _LOGGER.error(
                "E-Distribuzione non ha confermato l'invio del codice OTP "
                "(nessuno dei messaggi attesi %r nella risposta, lunga %d "
                "caratteri). Se il codice non arriva né via email né via "
                "SMS, allega otp_send_debug.html alla segnalazione.",
                _MARCATORI_OTP_INVIATO,
                len(body),
            )
            _salva_pagina_debug(body, "otp_send_debug.html")

        self._analizza_pagina_otp(body)

    # -- Steps 5-8: OTP validation + token exchange -----------------------

    async def async_submit_otp(self, otp_code: str) -> OAuthTokens:
        """Submit the OTP and complete the OAuth2 code exchange."""
        if self._flow.view_state is None:
            raise AuthError("async_begin_login() deve riuscire prima di async_submit_otp()")

        next_url = await self._sottometti_codice_otp(otp_code)
        consent_html = await self._scarica_pagina_dopo_otp(next_url)
        auth_code = await self._estrai_codice_autorizzazione(consent_html)
        return await self._async_exchange_code(auth_code)

    async def _sottometti_codice_otp(self, otp_code: str) -> str:
        """Step 5: POST the form with the code; returns the URL found in the
        response's meta Location tag."""
        headers = {"User-Agent": _MOBILE_USER_AGENT, "Faces-Request": "partial/ajax"}
        data = self._form_convalida(otp_code)

        url = self._su_host(self._flow.form_action_url or LOGINFLOW_URL)
        async with self._session.post(url, data=data, headers=headers) as resp:
            body = await _leggi_testo(resp)

        self._verifica_non_troppe_sessioni(body, "otp_submit_response_debug.html")

        if "Codice OTP" in body and "errato" in body.lower():
            raise InvalidOtp(body[:500])

        loc_match = re.search(r'name="Location"\s+content="([^"]+)"', body)
        if not loc_match:
            _log_parsing_failure_context(body, "meta Location dopo l'invio dell'OTP")
            _salva_pagina_debug(body, "otp_submit_response_debug.html")
            raise ParsingError(
                "Redirect (meta Location) non trovato nella risposta dopo "
                f"l'invio dell'OTP (risposta lunga {len(body)} caratteri - "
                "vedi log per un'anteprima)"
            )
        next_url = unquote(loc_match.group(1))
        if next_url.startswith("/"):
            next_url = self._origin + next_url
        return self._su_host(next_url)

    async def _scarica_pagina_dopo_otp(self, next_url: str) -> str:
        """Step 6: GET the page the redirect points to - normally it then
        triggers a JS redirect to eneldist://redirect?code=..., which aiohttp
        cannot follow (custom scheme, not HTTP): the code is scraped from the
        text below, not by navigating."""
        headers = {"User-Agent": _MOBILE_USER_AGENT}
        async with self._session.get(next_url, headers=headers) as resp:
            return await _leggi_testo(resp)

    async def _estrai_codice_autorizzazione(self, consent_html: str) -> str:
        """Step 7: find code/state in the page. If absent, it is this account's
        first authorization: Salesforce shows an explicit consent screen
        ("Consentire l'accesso?") instead of returning the code right away - it
        must be approved on the user's behalf, then searched again. From the
        second time on the consent stays stored on Salesforce and this branch is
        no longer run."""
        code_match = re.search(r"[?&]code=([^&'\"]+)", consent_html)
        state_match = re.search(r"[?&]state=([^&'\"]+)", consent_html)

        if not code_match:
            risposta_consenso = await self._async_approva_consenso(consent_html)
            if risposta_consenso is not None:
                consent_html = risposta_consenso
                code_match = re.search(r"[?&]code=([^&'\"]+)", consent_html)
                state_match = re.search(r"[?&]state=([^&'\"]+)", consent_html)

        if not code_match:
            _log_parsing_failure_context(
                consent_html, "authorization code sulla pagina di consenso"
            )
            _salva_pagina_debug(consent_html, "consent_page_debug.html")
            raise ParsingError(
                "Authorization code non trovato nella risposta della pagina "
                f"di consenso (pagina lunga {len(consent_html)} caratteri - "
                "vedi log per un'anteprima)"
            )

        self._valida_state(state_match)
        return unquote(code_match.group(1))

    def _valida_state(self, state_match: re.Match[str] | None) -> None:
        """The 'state' parameter is OAuth's standard CSRF protection: generated
        and sent by us in _carica_pagina_login, it should come back identical.
        Only a warning, not a blocking error: a false positive here would break
        an otherwise valid login (e.g. encoding differences)."""
        if state_match and unquote(state_match.group(1)) != self._oauth_state:
            _LOGGER.warning(
                "State OAuth nella risposta non corrisponde a quello inviato "
                "(atteso %r, ricevuto %r) - procedo comunque, ma segnalalo se "
                "il login inizia a fallire qui",
                self._oauth_state,
                state_match.group(1),
            )

    async def _async_approva_consenso(self, html: str) -> str | None:
        """Press "Consenti" on Salesforce's OAuth consent screen.

        Returns the text to search the authorization code in: the response's
        Location if there is a redirect (typically to eneldist://redirect?code=...,
        which aiohttp cannot follow because it is not an HTTP scheme), otherwise
        the response body. Returns None if this page is not a recognisable
        consent screen, so the caller proceeds with its usual parsing error.
        """
        form = self._estrai_form_consenso(html)
        if form is None:
            return None

        action_url, dati = form
        action_url = self._su_host(action_url)
        _LOGGER.info(
            "Schermata di consenso OAuth rilevata (prima autorizzazione di "
            "questo account): confermo con %r",
            dati.get("save"),
        )
        headers = {
            "User-Agent": _MOBILE_USER_AGENT,
            "Content-Type": "application/x-www-form-urlencoded",
            "Origin": self._origin,
            "Referer": f"{self._origin}/PortaleClienti/",
        }
        # allow_redirects=False: the redirect points to the app's custom scheme
        # (eneldist://), which aiohttp cannot follow - the code is in the
        # Location, which we can read directly here.
        async with self._session.post(
            action_url, data=dati, headers=headers, allow_redirects=False
        ) as resp:
            location = resp.headers.get("Location")
            body = await _leggi_testo(resp)
        return location or body

    @staticmethod
    def _estrai_form_consenso(html: str) -> tuple[str, dict[str, str]] | None:
        """Find the consent screen's form and build the payload to send back: all
        the hidden fields as they are, plus the approval button.

        Returns (action_url, data) or None if there is no form with a
        recognisable approval button.
        """
        for form_match in re.finditer(r"<form[^>]*>.*?</form>", html, re.IGNORECASE | re.DOTALL):
            blocco = form_match.group(0)
            approva: tuple[str, str] | None = None
            for input_match in re.finditer(r"<input[^>]*>", blocco, re.IGNORECASE):
                tag = input_match.group(0)
                if not re.search(r'type="submit"', tag, re.IGNORECASE):
                    continue
                nome = re.search(r'name="([^"]*)"', tag)
                valore = re.search(r'value="([^"]*)"', tag)
                if not nome or not valore:
                    continue
                etichetta = html_lib.unescape(valore.group(1))
                if etichetta.strip().lower() in _ETICHETTE_CONSENSO:
                    approva = (nome.group(1), etichetta)
                    break
            if approva is None:
                continue

            dati = {}
            for input_match in re.finditer(r"<input[^>]*>", blocco, re.IGNORECASE):
                tag = input_match.group(0)
                if not re.search(r'type="hidden"', tag, re.IGNORECASE):
                    continue
                nome = re.search(r'name="([^"]*)"', tag)
                if not nome:
                    continue
                valore = re.search(r'value="([^"]*)"', tag)
                # The values in the HTML are escaped (&amp;, &#39;): they must be
                # unescaped, otherwise the server receives fields different from
                # the ones it generated (save_new_url and source are full URLs
                # with parameters).
                dati[nome.group(1)] = html_lib.unescape(valore.group(1)) if valore else ""
            dati[approva[0]] = approva[1]

            action = re.search(r'<form[^>]*action="([^"]*)"', blocco, re.IGNORECASE)
            action_url = html_lib.unescape(action.group(1)) if action else ""
            if not action_url:
                return None
            if action_url.startswith("/"):
                # Static method: builds a primary-host URL, which the caller
                # rewrites onto the active host via _su_host.
                action_url = f"https://{SF_HOST_PRINCIPALE}" + action_url
            return action_url, dati

        return None

    @staticmethod
    def _verifica_non_troppe_sessioni(testo: str, nome_file_debug: str | None = None) -> None:
        """Raise TroppeSessioni if the text contains one of the known markers.

        Centralises a check that in the original protocol appears in three
        different points of the flow (loginUser response, submit without code,
        submit with code) with the exact same meaning."""
        if not _contiene(testo, _MARCATORI_TROPPE_SESSIONI):
            return
        if nome_file_debug:
            _salva_pagina_debug(testo, nome_file_debug)
        raise TroppeSessioni(testo[:500])

    # -- Token exchange/refresh ---------------------------------------------

    async def _async_exchange_code(self, code: str) -> OAuthTokens:
        """Step 8: exchange the authorization code for a token pair."""
        data = {
            "code": code,
            "code_verifier": self._code_verifier,
            "redirect_uri": OAUTH_REDIRECT_URI,
            "client_id": OAUTH_CLIENT_ID,
            "grant_type": "authorization_code",
        }
        async with self._session.post(self._su_host(OAUTH_TOKEN_URL), data=data) as resp:
            payload = self._json_token(await _leggi_testo(resp), resp.status)
        return self._tokens_from_payload(payload)

    async def async_refresh_access_token(self, refresh_token: str) -> OAuthTokens:
        """Get a fresh access_token. No Aura/OTP involved - this is the path the
        integration uses on every normal start/renewal.

        Tries the primary host first (so it returns to the official domain as
        soon as Enel lifts the block), falling back to the direct host if the
        primary answers with the anti-bot page.
        """
        self._host = SF_HOST_PRINCIPALE
        try:
            return await self._async_refresh_su_host(refresh_token)
        except AccessoBloccato:
            if self._host == SF_HOST_DIRETTO:
                raise
            _LOGGER.warning(
                "Refresh bloccato su %s, riprovo via %s", SF_HOST_PRINCIPALE, SF_HOST_DIRETTO
            )
            self._host = SF_HOST_DIRETTO
            return await self._async_refresh_su_host(refresh_token)

    async def _async_refresh_su_host(self, refresh_token: str) -> OAuthTokens:
        data = {
            "grant_type": "refresh_token",
            "refresh_token": refresh_token,
            "client_id": OAUTH_CLIENT_ID,
        }
        async with self._session.post(self._su_host(OAUTH_TOKEN_URL), data=data) as resp:
            text = await _leggi_testo(resp)
            if resp.status != 200:
                raise AuthError(f"Scambio del refresh_token fallito ({resp.status}): {text[:300]}")
            payload = self._json_token(text, resp.status)
        # Salesforce does not always return a new refresh_token on refresh - the
        # old one is kept if a new one does not arrive.
        payload.setdefault("refresh_token", refresh_token)
        return self._tokens_from_payload(payload)

    @staticmethod
    def _json_token(testo: str, status: int) -> dict:
        """JSON of the token endpoint; an HTML page in its place is a
        ParsingError (hence an AuthError), not a generic ValueError."""
        try:
            return json.loads(testo)
        except json.JSONDecodeError as err:
            raise ParsingError(
                f"Risposta non-JSON dal token endpoint (status {status}): {testo[:200]!r}"
            ) from err

    @staticmethod
    def _tokens_from_payload(payload: dict) -> OAuthTokens:
        try:
            return OAuthTokens(
                access_token=payload["access_token"],
                refresh_token=payload["refresh_token"],
                instance_url=payload.get("instance_url", ""),
                id_token=payload.get("id_token"),
                raw=payload,
            )
        except KeyError as err:
            raise ParsingError(f"Campo atteso mancante nella risposta del token endpoint: {err}") from err

    # -- HTML/JSON scraping --------------------------------------------------
    # The parts most likely to need fixing against a fresh HAR.

    @staticmethod
    def _estrai_fwuid(html: str) -> str:
        # Direct form: literal "fwuid":"<value>" in embedded JSON/JS.
        match = re.search(r'"fwuid"\s*:\s*"([^"]+)"', html)
        if match:
            return match.group(1)

        # Percent-encoded form: the Aura context blob is embedded directly in the
        # PATH of a <script src="..."> URL, not in a JS variable:
        #   <script src="/PortaleClienti/s/sfsites/l/%7B%22mode%22...
        #     %22fwuid%22%3A%22<value>%22...%7D/app.js">
        # It must be like this because literal quotes inside a src="..." attribute
        # would break the HTML parsing.
        match = re.search(r"%22fwuid%22%3A%22([^%]+)%22", html)
        if match:
            return match.group(1)

        raise ParsingError("fwuid non trovato sulla pagina di login")

    @staticmethod
    def _estrai_loaded(html: str) -> str:
        """Extract the raw value (JSON, as a string) of the 'loaded' field from
        the same bootstrap blob fwuid is extracted from - e.g.
        '{"APPLICATION@markup://siteforce:loginApp2":"1628_TW-..."}'.

        Needed because aura.context with 'loaded':{} (empty) is rejected by the
        server with a generic AuraClientInputException: the real 'loaded' value
        is not empty and must be sent back identically.

        Returns '{}' (string) if not found, so the caller degrades to the
        previous behaviour instead of failing here - the real failure will come
        anyway from the server on loginUser, with the error already diagnosed
        there.
        """
        match = re.search(r'"loaded"\s*:\s*(\{[^}]*\})', html)
        if match:
            return match.group(1)

        match = re.search(r"%22loaded%22%3A(%7B.*?%7D)", html)
        if match:
            return unquote(match.group(1))

        return "{}"

    @staticmethod
    def _estrai_url_redirect_js(html: str) -> str:
        """The frontdoor.jsp page is a bridge that redirects to the real OTP form
        with window.location.replace('URL') (JavaScript, not an HTTP redirect) -
        a browser follows it on its own, here it must be extracted by hand and
        requested with an explicit GET.

        The URL inside replace() is already absolute and correctly
        percent-encoded (it is inside a JS string, not an HTML attribute), so
        there is no double-encoding issue as elsewhere in this file - it is used
        as-is.
        """
        match = re.search(r"window\.location\.replace\('([^']+)'\)", html)
        if match:
            return match.group(1)

        # Fallback: some variants of this Salesforce page use
        # window.location.href instead of .replace(...).
        match = re.search(r"window\.location\.href\s*=\s*'([^']+)'", html)
        if match:
            return match.group(1)

        _log_parsing_failure_context(html, "window.location.replace(...) su pagina frontdoor")
        raise ParsingError(
            "Redirect JavaScript verso il form OTP non trovato sulla pagina "
            f"di frontdoor (pagina lunga {len(html)} caratteri - vedi log "
            "per un'anteprima)"
        )

    def _analizza_pagina_otp(self, html: str) -> None:
        """Extract from the OTP form's Visualforce page everything needed to
        submit it (ViewState/CSRF + dynamic field names), saving it in
        self._flow."""

        def trova(nome_campo: str) -> str:
            # Search the whole <input ...> tag that contains this 'name'
            # attribute, then 'value' INSIDE it - independent of the order the
            # two attributes appear in the tag.
            tag_match = re.search(rf'<input[^>]*name="{re.escape(nome_campo)}"[^>]*>', html)
            if not tag_match:
                _log_parsing_failure_context(html, nome_campo)
                raise ParsingError(
                    f"Campo '{nome_campo}' non trovato sulla pagina OTP "
                    f"(pagina lunga {len(html)} caratteri - vedi log per un'anteprima)"
                )
            value_match = re.search(r'value="([^"]*)"', tag_match.group(0))
            if not value_match:
                raise ParsingError(
                    f"Campo '{nome_campo}' trovato ma senza attributo 'value' "
                    f"leggibile: {tag_match.group(0)!r}"
                )
            return value_match.group(1)

        self._flow.view_state = trova("com.salesforce.visualforce.ViewState")
        self._flow.view_state_version = trova("com.salesforce.visualforce.ViewStateVersion")
        self._flow.view_state_mac = trova("com.salesforce.visualforce.ViewStateMAC")
        self._flow.view_state_csrf = trova("com.salesforce.visualforce.ViewStateCSRF")

        # The field prefixes below are generated by Salesforce and can change
        # between deploys: they are discovered dynamically instead of trusting
        # only the hardcoded defaults (used as a fallback above).
        otp_field = re.search(r'name="([^"]*OTP_Input[^"]*)"', html)
        if otp_field:
            self._flow.otp_field_name = otp_field.group(1)

        # The page has TWO fields with "Richiedi_nuovo_OTP" in the name: a visible
        # checkbox (element___input____...) and a hidden field that mirrors it
        # (element___hidden____...), updated by a JS onclick - it is the latter
        # that must be submitted. A generic regex finds the checkbox first (it
        # appears earlier in the HTML), causing the wrong field to be sent: the
        # server then treated the code submission as yet another resend request
        # instead of a validation.
        resend_field = re.search(
            r'name="([^"]*element___hidden____Richiedi_nuovo_OTP[^"]*)"', html
        )
        if resend_field:
            self._flow.resend_field_name = resend_field.group(1)
        resend_checkbox = re.search(
            r'name="([^"]*element___input____Richiedi_nuovo_OTP[^"]*)"', html
        )
        if resend_checkbox:
            self._flow.resend_checkbox_field_name = resend_checkbox.group(1)
        next_field = re.search(r'name="([^"]*nextAjax[^"]*)"', html)
        if next_field:
            self._flow.next_field_name = next_field.group(1)

        form_action = re.search(r'<form[^>]+action="([^"]+)"', html)
        if form_action:
            action = form_action.group(1)
            self._flow.form_action_url = self._su_host(
                action if action.startswith("http") else f"{self._origin}{action}"
            )
